### ISSUE TITLE
need to send notifications to close/reopen the app for location tracking purposes

### ISSUE THREAD

**Issue by jenniewerner** [NUDelta/ce-platform#29]
- See the _sendPush or notify functions
- Based on our testing, I'm thinking send once in the morning, ~9am and once in the evening ~5pm?

**Comment by kapil1garg** [comment]
Will all users be in Chicago? Just thinking about timezone considerations (will hardcore if true)...

**Comment by jenniewerner** [comment]
Don't assume all users will be in Chicago. Ideally we'll get people
elsewhere too. Can hardcore people time zones if that helps. Or they're in
a users location/affordance.

**Comment by jenniewerner** [comment]
basics working -- ideally it would first check how long it had been since their location updated

**Comment by kapil1garg** [comment]
@youralien this issue isn't relevant anymore right?

**Comment by youralien** [comment]
@kapil1garg correct, and in fact I deleted the cron job that resolved this.
