### ISSUE TITLE
Cannot read property _id of null

### ISSUE THREAD

**Issue by aspin** [NUDelta/ce-platform#3]
This is being called on the participate and result templates occasionally. Seems to be as a result of some needed subscription refactoring (namely `this.data` is undefined) -- this happens specifically when navigating back from results to participate.

**Comment by aspin** [comment]
This actually affects our ability to open up pages from push notification as well (happening only on the results page for me though).

**Comment by ryanmadden** [comment]
Repro instructions? I was going back and forth in different orders and couldn't get it to happen. 

Side note: not sure how you're browsing between these but remember that (for better or for worse, currently) the _id in the route for participate is an experience ID and the _id in the route for results is an incident ID

**Comment by aspin** [comment]
Ahhh k that would be the issue. Hm.

**Comment by ryanmadden** [comment]
I patched it, we can talk about a redesign of the participate/results workflow but this will work for now

b73b778ac22e927a3fc76212df130af8e9c573e1
