### ISSUE TITLE
Remake testing detectors with Yelp v3

### ISSUE THREAD

**Issue by kapil1garg** [NUDelta/ce-platform#39]
Detectors in `imports/api/Testing/testingconstants.js` should be re-written using the new categories for Yelp v3. I think the best time to do this will be after Ryan finishes up with Affinder's transition, but **note that we will not be able to test once the endpoints shut down on June 30, 2018.**

**Comment by youralien** [comment]
New detectors created, and new bugs squashed, ending with this commit in "experience-timing"
https://github.com/NUDelta/ce-platform/commit/ee147309d2997420c64e947d06462d7942b24da0
