### ISSUE TITLE
New experiences not showing up as "participate now!" options on home page

### ISSUE THREAD

**Issue by sgnachreiner** [NUDelta/ce-platform#4]
To reproduce: create a new experience, start it, and go to the home page. It does not show up with a big "participate now!" button in blue at the top, but it does show up as an experience a person can view the results of below.

**Comment by ryanmadden** [comment]
The experiences isn't getting pushed onto a user's profile.activeExperiences array for some reason, even though the relevant function is getting called. I'll work it out
