### ISSUE TITLE
Running multiple instances of the same experience causes bad things to happen

### ISSUE THREAD

**Issue by aspin** [NUDelta/ce-platform#8]
This is because of how we set a single active experience on experience ids.

**Comment by ryanmadden** [comment]
Is this something we want to support?

**Comment by aspin** [comment]
Fair question, idk, but we should probably leave this issue here as a reminder if we do get to that?

-- 
Kevin Chen


On May 2, 2016 at 5:23:17 PM, Ryan Madden (notifications@github.com) wrote:

Is this something we want to support?
